apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dso-demo-azure
  name: dso-demo-azure
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dso-demo-azure
  type: LoadBalancer
status:
  loadBalancer: {}
